import { GeistMono } from 'geist/font/mono';
import { GeistSans } from 'geist/font/sans';

import type { PropsWithChildren } from 'react';

import type { Metadata, NextPage } from 'next';

import { cn } from '@/lib/tailwind-utils';
import { AosProvider } from '@/providers/aos-provider';
import { StylesProvider } from '@/providers/styles-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn(GeistSans.variable, GeistMono.variable)}>
        <StylesProvider />
        {children}
        <AosProvider />
      </body>
    </html>
  );
};

export default RootLayout;
